
import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  Share,
} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';

export default function ReportResultScreen({ route, navigation }) {
  const { result } = route.params;

  const handleShare = async () => {
    try {
      const shareContent = `Medical Report Analysis

Diagnosis: ${result.diagnosis}

Prescription: ${result.prescription}

Recommendations:
${result.recommendations.map(rec => `• ${rec}`).join('\n')}

Confidence: ${Math.round(result.confidence * 100)}%

Generated by HealthAI MVP`;

      await Share.share({
        message: shareContent,
        title: 'Medical Report Analysis',
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  const getConfidenceColor = (confidence) => {
    if (confidence >= 0.8) return '#4CAF50';
    if (confidence >= 0.6) return '#FF9800';
    return '#F44336';
  };

  const getConfidenceText = (confidence) => {
    if (confidence >= 0.8) return 'High Confidence';
    if (confidence >= 0.6) return 'Moderate Confidence';
    return 'Low Confidence';
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView style={styles.scrollView}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerTop}>
            <TouchableOpacity 
              style={styles.backButton}
              onPress={() => navigation.goBack()}
            >
              <Icon name="arrow-back" size={24} color="#333" />
            </TouchableOpacity>
            <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
              <Icon name="share-outline" size={24} color="#2196F3" />
            </TouchableOpacity>
          </View>
          
          <Text style={styles.title}>Analysis Results</Text>
          <Text style={styles.subtitle}>
            Report processed on {new Date(result.timestamp).toLocaleDateString()}
          </Text>
        </View>

        {/* Confidence Score */}
        <View style={styles.confidenceCard}>
          <View style={styles.confidenceHeader}>
            <Icon name="analytics" size={24} color={getConfidenceColor(result.confidence)} />
            <Text style={styles.confidenceTitle}>AI Analysis Confidence</Text>
          </View>
          
          <View style={styles.confidenceScore}>
            <Text style={[styles.confidencePercentage, { color: getConfidenceColor(result.confidence) }]}>
              {Math.round(result.confidence * 100)}%
            </Text>
            <Text style={[styles.confidenceLabel, { color: getConfidenceColor(result.confidence) }]}>
              {getConfidenceText(result.confidence)}
            </Text>
          </View>
          
          <View style={styles.confidenceBar}>
            <View 
              style={[
                styles.confidenceProgress, 
                { 
                  width: `${result.confidence * 100}%`,
                  backgroundColor: getConfidenceColor(result.confidence)
                }
              ]} 
            />
          </View>
        </View>

        {/* Diagnosis Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="medical" size={20} color="#2196F3" />
            <Text style={styles.sectionTitle}>Diagnosis</Text>
          </View>
          
          <View style={styles.card}>
            <Text style={styles.diagnosisText}>{result.diagnosis}</Text>
          </View>
        </View>

        {/* Prescription Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="receipt" size={20} color="#4CAF50" />
            <Text style={styles.sectionTitle}>Prescription & Treatment</Text>
          </View>
          
          <View style={styles.card}>
            <Text style={styles.prescriptionText}>{result.prescription}</Text>
          </View>
        </View>

        {/* Recommendations Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="bulb" size={20} color="#FF9800" />
            <Text style={styles.sectionTitle}>Recommendations</Text>
          </View>
          
          <View style={styles.card}>
            {result.recommendations.map((recommendation, index) => (
              <View key={index} style={styles.recommendationItem}>
                <View style={styles.recommendationBullet}>
                  <Text style={styles.bulletText}>{index + 1}</Text>
                </View>
                <Text style={styles.recommendationText}>{recommendation}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Important Notice */}
        <View style={styles.noticeCard}>
          <View style={styles.noticeHeader}>
            <Icon name="warning" size={20} color="#F44336" />
            <Text style={styles.noticeTitle}>Important Notice</Text>
          </View>
          
          <Text style={styles.noticeText}>
            This AI analysis is for informational purposes only and should not replace professional medical advice. 
            Always consult with qualified healthcare providers for proper diagnosis and treatment.
          </Text>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionButtons}>
          <TouchableOpacity 
            style={styles.primaryButton}
            onPress={() => navigation.navigate('Chat')}
          >
            <Icon name="chatbubble" size={20} color="white" />
            <Text style={styles.primaryButtonText}>Ask AI Questions</Text>
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.secondaryButton}
            onPress={() => navigation.navigate('Upload')}
          >
            <Icon name="add" size={20} color="#2196F3" />
            <Text style={styles.secondaryButtonText}>Upload Another Report</Text>
          </TouchableOpacity>
        </View>

        {/* Report Details */}
        <View style={styles.detailsCard}>
          <Text style={styles.detailsTitle}>Report Details</Text>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>File Name:</Text>
            <Text style={styles.detailValue}>{result.filename}</Text>
          </View>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Analysis Date:</Text>
            <Text style={styles.detailValue}>
              {new Date(result.timestamp).toLocaleString()}
            </Text>
          </View>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Report ID:</Text>
            <Text style={styles.detailValue}>{result.id}</Text>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  backButton: {
    padding: 8,
  },
  shareButton: {
    padding: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  confidenceCard: {
    backgroundColor: 'white',
    margin: 20,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  confidenceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  confidenceTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginLeft: 8,
  },
  confidenceScore: {
    alignItems: 'center',
    marginBottom: 16,
  },
  confidencePercentage: {
    fontSize: 32,
    fontWeight: 'bold',
  },
  confidenceLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },
  confidenceBar: {
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  confidenceProgress: {
    height: '100%',
    borderRadius: 4,
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginLeft: 8,
  },
  card: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  diagnosisText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#333',
  },
  prescriptionText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#333',
  },
  recommendationItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  recommendationBullet: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FF9800',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  bulletText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  recommendationText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: '#333',
  },
  noticeCard: {
    backgroundColor: '#ffebee',
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#F44336',
  },
  noticeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  noticeTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F44336',
    marginLeft: 8,
  },
  noticeText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#d32f2f',
  },
  actionButtons: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  primaryButton: {
    backgroundColor: '#2196F3',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  secondaryButton: {
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2196F3',
  },
  secondaryButtonText: {
    color: '#2196F3',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  detailsCard: {
    backgroundColor: 'white',
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  detailLabel: {
    fontSize: 14,
    color: '#666',
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    color: '#333',
    flex: 2,
    textAlign: 'right',
  },
});